### ISSUE TITLE
Configuration data is reset at reinstall 

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-reporting#23]
When you reinstalled reportserver to get my patch working of course also your configuration data was reset. Your birt report imports an external css file and for this to work the birt.library.folder in reportengines.cf need to be set to the correct folder. I've changed this to point to the correct folder and it seems fine now. 

As there was nothing in the logfiles that gave any indication what was wrong: A good idea when there are problems with a birt report is to always try an html export: This also shows errors that occured inside the birt engine. 

https://support.datenwerke.net/support/tickets/162

**Comment by zzgvh** [comment]
I got the Testing/Gabriels-template-29jan report working. I think the issue was that the Selecten mode for the District was set to Multiselect. Confirmed by creating a new report,  "Testing/Gabriel testing 29jan template" based on the download from issue 162, and that also works works fine.
